###
# Contains hooks that are fired when an environment is built. See https://docs.platform.sh/configuration/app/build.html#build-hook
###

################################
###          CORE           ###
###############################
# Ensures that if an error occurs in one of our hooks it will fail the build
set -e

################################
###        WORDPRESS        ###
###############################
# Copy manually-provided plugins into the plugins directory.
# This allows manually-provided and composer-provided plugins to coexist.
rsync -a plugins/ public/wp-content/plugins/
# create a symlink to our actual file in the root of mu-plugins
./scripts/digitalservice/setup-mu-plugins.sh

################################
###     Project Specific    ###
###############################
# Add any additional project specific build hooks you need in the environment after this line

