operations:
  auto-update:
    command: |
      git remote add upstream git@github.com:gilzow/wp-upstream-demo.git
      git fetch --all
      git pull upstream main
      composer update
      git add --all
      confirm=$(git status --porcelain=1);
      if [ -z "${confirm}" ]; then
          echo "No changes to commit."
      else
          git commit -m "Auto updated via source operations"
      fi
